### ISSUE TITLE
NullPointerException in a select() query

### ISSUE THREAD

**Issue by Vrael** [pardom-zz/ActiveAndroid#109]
Manifest

``` xml
<application
    <!-- other not important data -->
    android:name="com.myapp.App">

    <meta-data android:name="AA_DB_NAME" android:value="myapp.db" />
    <meta-data android:name="AA_DB_VERSION" android:value="1" />

    <activity android:name=".MainActivity" >
       <!-- other not important data -->
    </activity>
</application>
```

Foo class

``` java
@Table(name = "Myclases")
public class MyClass extends Model {

    @Column(name = "foo")
    public String foo;

    public static List<String> getAll(){
        return new Select()
                .from(MyClass.class)
                .execute();
    }
}
```

Method in MainActivity in a Fragment....

``` java
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    List<String> myList = MyClass.getAll();  //HERE IT FIRES THE ISSUE!
}
```

Error!

``` java
java.lang.NullPointerException
09-02 11:09:05.365: E/AndroidRuntime(30818):    at com.activeandroid.Cache.getTableName(Cache.java:152)
09-02 11:09:05.365: E/AndroidRuntime(30818):    at com.activeandroid.query.From.toSql(From.java:146)
09-02 11:09:05.365: E/AndroidRuntime(30818):    at com.activeandroid.query.From.execute(From.java:205)
09-02 11:09:05.365: E/AndroidRuntime(30818):    at com.emanga.MainActivity$SectionFragment.onCreateView(MainActivity.java:151)
```

**Comment by leonardoxh** [comment]
Here too, after the last commit the tables are not created, seams now we have set the model classes, with AA_MODELS on AndroidManifest or via Configuration object

**Comment by nologinatgit** [comment]
Guys, there supposed to be tests that are responsible to check if the modifications don't cause any error in the system yet there are easily reproducible NPEs after merges to master branch. I use AA in an app that is published, so I am very careful of upgrading my AA because last time AA stopped working after a merge (luckily it was prior to the publish).
Please, check the code with tests before merging them.

**Comment by leonardoxh** [comment]
With this version the models are "not discovered" automatically, the fast way is 

Configuration.Builder config = new Configuration.Builder(Context);
config.addModelClasses(Model1.class, Model2.class);

And in the application class -> ActiveAndroid.initialize(config);

Its much more difficult now rsrs...

**Comment by pardom-zz** [comment]
I'll fix this ASAP. Checkout an old commit for now, as no additional features were added.

**Comment by pardom-zz** [comment]
commit b4b2c090c26463acff97e869e652170629e3256b
Author: Michael Pardo kensuke155@gmail.com
Date:   Mon Sep 2 16:58:51 2013 -0400

```
Fix check that source path is not a directory.
```

**Comment by Vrael** [comment]
Ok I just did a pull with the new commit, but when I compile with maven the tests fail.

Many error messages start like this:

``` maven
[INFO] emulator-5554_Galaxy_Nexus:       Start [4/32]: com.activeandroid.test.query.DeleteTest#testFrom
[INFO] emulator-5554_Galaxy_Nexus:       ERROR:com.activeandroid.test.query.DeleteTest#testFrom
[INFO] emulator-5554_Galaxy_Nexus:       java.lang.NullPointerException
at com.activeandroid.Cache.getTableName(Cache.java:152)
at com.activeandroid.query.From.toSql(From.java:146)
at com.activeandroid.test.query.SqlableTestCase.assertSqlEquals(SqlableTestCase.java:24)
at com.activeandroid.test.query.DeleteTest.testFrom(DeleteTest.java:28)
at java.lang.reflect.Method.invokeNative(Native Method)
....
```

**Comment by ryanoglesby08** [comment]
Please reopen this issue. I have just checked out the latest commit and am seeing the same error messages as @Vrael described above. I am evaluating this framework for use on a large project, but with so many failing tests I am extremely unlikely to use it.

32 Tests run, 18 failures. All for the same reason.

```
[INFO]   Tests run: 32,  Failures: 0,  Errors: 18
```

```
[INFO] emulator-5554_teacher-emulator_unknown_AndroidSDKbuiltforx86 :       java.lang.NullPointerException
at com.activeandroid.Cache.getTableName(Cache.java:152)
at com.activeandroid.query.Update.toSql(Update.java:43)
at com.activeandroid.query.Set.toSql(Set.java:70)
at com.activeandroid.test.query.SqlableTestCase.assertSqlEquals(SqlableTestCase.java:24)
at com.activeandroid.test.query.UpdateTest.testUpdateWhereWithArguments(UpdateTest.java:47)
```

**Comment by brainv** [comment]
@ryanoglesby08 any news on your issue? want to try this also in a large project.

**Comment by SeanPONeil** [comment]
All tests currently pass

**Comment by brainv** [comment]
@SeanPONeil this is my first time to use this, but still getting NullPointerException

```
03-04 03:39:03.891: E/AndroidRuntime(10613): Caused by: java.lang.NullPointerException
03-04 03:39:03.891: E/AndroidRuntime(10613):    at com.activeandroid.Cache.getTableName(Unknown Source)
03-04 03:39:03.891: E/AndroidRuntime(10613):    at com.activeandroid.query.From.toSql(Unknown Source)
03-04 03:39:03.891: E/AndroidRuntime(10613):    at com.activeandroid.query.From.executeSingle(Unknown Source)
```

Included the jar from the ant build and followed the setting up 

```
        <meta-data android:name="AA_DB_NAME" android:value="Pickrand.db" />
        <meta-data android:name="AA_DB_VERSION" android:value="5" />
```

**Comment by SeanPONeil** [comment]
Try building the jar with `mvn clean install` and see if you get the same issue. Also, if you are using Proguard, make sure your @Table annotated classes are excluded.

**Comment by brainv** [comment]
I'm getting the same result @SeanPONeil 

```
...
03-04 03:59:40.031: E/AndroidRuntime(11686): FATAL EXCEPTION: main
03-04 03:59:40.031: E/AndroidRuntime(11686): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cmai.martin/com.cmai.martin.activity.MyAgentActivity_}: java.lang.NullPointerException
03-04 03:59:40.031: E/AndroidRuntime(11686):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2264)
03-04 03:59:40.031: E/AndroidRuntime(11686):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2314)
03-04 03:59:40.031: E/AndroidRuntime(11686):    at android.app.ActivityThread.access$600(ActivityThread.java:144)
03-04 03:59:40.031: E/AndroidRuntime(11686):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
03-04 03:59:40.031: E/AndroidRuntime(11686):    at android.os.Handler.dispatchMessage(Handler.java:99)
03-04 03:59:40.031: E/AndroidRuntime(11686):    at android.os.Looper.loop(Looper.java:150)
03-04 03:59:40.031: E/AndroidRuntime(11686):    at android.app.ActivityThread.main(ActivityThread.java:5147)
03-04 03:59:40.031: E/AndroidRuntime(11686):    at java.lang.reflect.Method.invokeNative(Native Method)
03-04 03:59:40.031: E/AndroidRuntime(11686):    at java.lang.reflect.Method.invoke(Method.java:511)
03-04 03:59:40.031: E/AndroidRuntime(11686):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
03-04 03:59:40.031: E/AndroidRuntime(11686):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
03-04 03:59:40.031: E/AndroidRuntime(11686):    at dalvik.system.NativeStart.main(Native Method)
03-04 03:59:40.031: E/AndroidRuntime(11686): Caused by: java.lang.NullPointerException
03-04 03:59:40.031: E/AndroidRuntime(11686):    at com.activeandroid.Cache.getTableName(Cache.java:156)
03-04 03:59:40.031: E/AndroidRuntime(11686):    at com.activeandroid.query.From.toSql(From.java:155)
03-04 03:59:40.031: E/AndroidRuntime(11686):    at com.activeandroid.query.From.executeSingle(From.java:227)
...
```

Result of `mvn clean install`

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] ActiveAndroid - Parent ............................ SUCCESS [13.015s]
[INFO] ActiveAndroid ..................................... SUCCESS [4:08.319s]
[INFO] ActiveAndroid - Tests ............................. SUCCESS [49.646s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8:41.921s
[INFO] Finished at: Tue Mar 04 03:57:31 PHT 2014
[INFO] Final Memory: 19M/81M
[INFO] ------------------------------------------------------------------------
```

**Comment by SeanPONeil** [comment]
Are you running ActiveAndroid.initialize() in your Application class?

**Comment by brainv** [comment]
I tried just now, but it gives same result.

Here's the code of my model

```
package com.cmai.martin.model;

import java.util.List;

import com.activeandroid.Model;
import com.activeandroid.annotation.Column;
import com.activeandroid.annotation.Table;
import com.activeandroid.query.Select;

@Table(name = "Settings")
public class Setting extends Model {

    @Column(name = "MediaDownloaded")
    public int mediaDownloaded;

    public static Setting getSetting() {

        Setting setting = new Select().from(Setting.class).executeSingle();

        if (setting == null) {
            setting = new Setting();
            setting.mediaDownloaded = 0;
            setting.save();
        }

        return setting;
    }

    public static List<Setting> getAll() {
        return new Select().from(Setting.class).execute();
    }
}
```

MyApplication

```
package com.cmai.martin;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;

import com.activeandroid.ActiveAndroid;

public class MyApplication extends com.activeandroid.app.Application {

    public void onCreate() {
        super.onCreate();

        ActiveAndroid.initialize(this);

        LocationLibrary.showDebugOutput(true);
        LocationLibrary.initialiseLibrary(getBaseContext(), 0, 2 * 60 * 1000,
                "com.cmai.martin");
    }


    public class Broadcast extends BroadcastReceiver {

        @Override
        public void onReceive(Context context, Intent intent) {
            final LocationInfo locationInfo = (LocationInfo) intent
                    .getSerializableExtra(LocationLibraryConstants.LOCATION_BROADCAST_EXTRA_LOCATIONINFO);

        }
    }

}
```

**Comment by SeanPONeil** [comment]
Try extending MyApplication from android.app.Application instead of com.activeandroid.app.Application, and call ActiveAndroid.initialize() with an explicit configuration like @leonardoxh described above.

**Comment by brainv** [comment]
This is the hardest part, where should I put this?

```
Configuration.Builder config = new Configuration.Builder(Context);
config.addModelClasses(Model1.class, Model2.class);
```

**Comment by brainv** [comment]
Putting in to `MyActivity.onCreate()` or `MyApplication.onCreate` didn't solve the problem

**Comment by SeanPONeil** [comment]
Replace Model1.class, Model2.class with Settings.class and the names of your other models

**Comment by brainv** [comment]
```
        Configuration.Builder config = new Configuration.Builder(this);
        config.addModelClasses(Setting.class);
```

Putting it on `MyActivity.onCreate()`. or MyApplication.onCreate didn't solve the problem

**Comment by SeanPONeil** [comment]
MyApplication should look like this

```
package com.cmai.martin;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;

import com.activeandroid.ActiveAndroid;

public class MyApplication extends Application {

    public void onCreate() {
        super.onCreate();

        Configuration.Builder config = new Configuration.Builder(this);
        config.addModelClasses(Setting.class);
        ActiveAndroid.initialize(config);

        LocationLibrary.showDebugOutput(true);
        LocationLibrary.initialiseLibrary(getBaseContext(), 0, 2 * 60 * 1000,
                "com.cmai.martin");
    }


    public class Broadcast extends BroadcastReceiver {

        @Override
        public void onReceive(Context context, Intent intent) {
            final LocationInfo locationInfo = (LocationInfo) intent
                    .getSerializableExtra(LocationLibraryConstants.LOCATION_BROADCAST_EXTRA_LOCATIONINFO);

        }
    }

}
```

**Comment by brainv** [comment]
@SeanPONeil same result. *I'm gonna cry now

**Comment by SeanPONeil** [comment]
Let's take troubleshooting off of this issue. Can you email me at oneilse14@gmail.com?

**Comment by brainv** [comment]
OK, sent you email.

**Comment by brainv** [comment]
created a sample project with the said issue https://github.com/brainv/SampleActiveAndroid

**Comment by joshuapinter** [comment]
@SeanPONeil CC me on the troubleshooting. I'm having a look right now. There's a good chance it has something to do with that pull request...

**Comment by brainv** [comment]
@joshuapinter @SeanPONeil created a repo of the sample app. pushed the added files from @SeanPONeil

**Comment by brainv** [comment]
It works now! Thanks for your help, @SeanPONeil. I'm excited to use this to my large project later!

**Comment by joshuapinter** [comment]
:thumbsup: Glad to hear. Nice one @SeanPONeil.

**Comment by ryanoglesby08** [comment]
@brainv @SeanPONeil Glad to hear this issue is resolved!  I have since moved off of my previous Android project, but when I have the need again I shall give ActiveAndroid another chance :)

**Comment by brainv** [comment]
@ryanoglesby08 we'll wait for your return :)
Right now I'm very happy of the result.

**Comment by qinjunli** [comment]
java.lang.NullPointerException
    at com.activeandroid.Cache.getTableName(Cache.java:156)
    at com.activeandroid.query.From.addFrom(From.java:169)
    at com.activeandroid.query.From.toSql(From.java:250)
    at com.activeandroid.query.From.execute(From.java:298)

I have downloaded and used the latest code, but the issue still exist. How did you solve this?

**Comment by neevek** [comment]
Same here, after 2 years, the issue still exists.

**Comment by jlhonora** [comment]
@neevek Did you define an empty constructor for your models? Check out: https://github.com/pardom/ActiveAndroid/wiki/Creating-your-database-model

**Comment by neevek** [comment]
@jlhonora No, I didn't define any custom constructors. this issue happens from time to time.

**Comment by svendvd** [comment]
The same here, my app ist used by 10.000 Users and I get 300 java.lang.NullPointerException
at com.activeandroid.Cache.getTableName after 6 months

**Comment by rcgonzalezf** [comment]
Same here :(

**Comment by antkz** [comment]
Same here.

It happens when I do some thing like this.

```
  Category cat = new Category();
  cat.name = "TEST NAME";
  cat.save();
```

`NullPointerException` happens when tries to call constructor.

I solved it by adding `android:name=".MyApplication"` in my `AndroidManifest.xml` file. If I don't write this, Android does not call my custom class which extends from `com.activeandroid.app.Application` when my app is started.

**Comment by pflammertsma** [comment]
I found a probable cause of this issue in #299. See my comments there explaining what I believe is causing the NullPointerException caused by getTableName().

**Comment by aliabbasjaffri** [comment]
I have been facing the similar issue. The reason is that there should be a default constructor in the model class with super() call in it.
I have been puling my hair all day because of it. 
Added a default constructor and the code works smooth.

**Comment by snowpong** [comment]
I'm seeing the same or similar issue, and we've already got a default constructor in the model classes with super() calls in it.

@pflammertsma can you explain how your patch fixes the NPE issue? Is Locale.English used in other read or writes in ActiveAndroid, and they simply just forgot in the lines you've changed?

I'm seeing this in the wild where it crashes during the activity onResume(..) in Cache.getTableName() but it's hard for me to reproduce this locally. Tips on how to provoke this crash when developing?

**Comment by pflammertsma** [comment]
The capitalization of table names is inconsistent, as it sometimes uses the
English locale, sometimes the device default. You can reproduce the issue
by setting your device to Turkish or Polish language.

**Comment by danpe** [comment]
It started crashing constantly after compiling with Android Studio 2.0

**Comment by gouthamiyyappan** [comment]
Same error and crash on launching the app after compiling with Android Studio 2.0

**Comment by lodlock** [comment]
@danpe @gouthamiyyappan this is due to instantrun. You can disable instantrun or attempt a check if the Cache object needs to be disposed. So replace your normal initialize with something like:

```
if (Cache.isInitialized() && Cache.getTableInfos().isEmpty()) {
        ActiveAndroid.dispose();
}
ActiveAndroid.initialize(HOWEVER_YOU_BUILD_YOUR_CONFIG);
```

It appears that the Cache's sModelInfo not retaining it's values after instantrun that's causing the problem.

**Comment by QuranPro** [comment]
i was facing this issue on android 7.0, android 5.0 was working fine , i disabled the instant run and it works like charm :)
