### ISSUE TITLE
Inheritance Support?

### ISSUE THREAD

**Issue by m2d2** [pardom-zz/ActiveAndroid#14]
Does ActiveAndroid models support inheritance? For example, if I had a Person model as the superclass and Attendee as a subclass, how would AA handle this? With Ruby on Rails, it is combined into a single table with values from subclasses added to the parent table. Any thoughts?

Also, there's a real need for rest of doco to be completed (schema migrations <-- important).

**Comment by ronnyek** [comment]
I believe the schema migration documentation is a separate issue all together, but I do agree. Even if you provide us a pointer in the correct direction, I'll even volunteer to write that documentation... (cant be clearing data every upgrade ;-)

**Comment by pardom-zz** [comment]
Inheritance is supported in that AA will find subclasses of Model no mater the inheritance level. However, it does not currently find private members of parent classes. This is in the roadmap.

I'm also currently look at ways to allow for documentation contribution (as I have little time to work on it), but you can always investigate the source code! :smiley:

**Comment by m2d2** [comment]
Thanks for the reply. Noted. 

I decided to look into schema migrations (I came up against it first). Ended up forking. https://github.com/m2d2/ActiveAndroid/wiki/Schema-migrations is the result. I will continue to improve on it and send a pull request when testing's done. I tried to follow rails style migrations.

**Comment by a99** [comment]
I don't think AA is handling inheritance correctly.

For example:

Class Pet
Class Dog extends Pet
Class Cat extends Pet

If I create 3 Dogs, and then 2 Cats
I expect 5 entries in Pets table.
I expect ids in Pets to be 1, 2, 3, 4, 5
I expect the ids in Dogs to be 1, 2, 3
I expect the ids in Cats to be 4, 5

Currently (as of 20/04/13 on master branch) the result is:
0 in Pets
3 in Dogs -> ids: 1, 2, 3
2 in Cats -> ids: 1, 2

---

The current behavior is unusable for model inheritance.

If the Pets has properties, because 0 Pets are created, they are not persisted to the database

Example:

Class Person has many Pets
Then Pets will have foreign key to Person, but since 0 Pets are created, no relationship is created

---

Please review and improve the current inheritance behavior

**Comment by xArthasx** [comment]
I think at this point of the library the inheritance of something different than Model will end up being ignored, thus not working

**Comment by a99** [comment]
I think that is what it is doing.
However, the model tables are being created for each data model in the database,

---

In Modeling section of the documentation, probably should mention all class must inherit from Model class, and provide suggestion for archiving inheritance.

Eg: using the flatten hierarchy table structure

**Comment by xArthasx** [comment]
As Pardom said in this thread:

> Inheritance is supported in that AA will find subclasses of Model no mater the inheritance level. However, it does not currently find private members of parent classes. This is in the roadmap.
> 
> I'm also currently look at ways to allow for documentation contribution (as I have little time to work on it), but you can always investigate the source code!

**Comment by dotnick** [comment]
> Inheritance is supported in that AA will find subclasses of Model no mater the inheritance level."

I'm having trouble getting AA to work with inheritance in my case. 

I have a Base Model which extends the AA Model and has 2 public fields. My model classes extend that Base Model class with more fields. 

I can see that the object has all the fields when I save but when I query the database the two fields of the base model are null. Is there any documentation on this? 
Thanks

**Comment by bkhall** [comment]
@pardom 
@dotnick 

I think the issue of missing inherited fields is caused by line 56 of the TableInfo class:

``` java
List<Field> fields = new ArrayList<Field>(Arrays.asList(type.getDeclaredFields()));
```

The getDeclaredFields() method does not include public fields from parent classes. It only looks at the concrete class in question. I was able to get inheritance to work by changing this line to:

``` java
List<Field> fields = new ArrayList<Field>(Arrays.asList(type.getFields()));
```

The getFields() method walks up the inheritance tree and returns all public fields found. Then line 59 through 64 weed out the fields that don't have a Column annotation.

Without the inherited public fields being found, the associated columns in the table are not created. Saving a class instance to the database loses the raw info. Then, when you load the info back from the table into a new class instance, the fields are not populated because there is not data present (missing columns), and are therefore null.

**Comment by WonderCsabo** [comment]
@bkhall
@pardom  

Actually `getFields()` only returns the public fields of the class. I don't think it would be a solution, because this library cannot require its users to follow a very bad pattern and use public fields in each model class. But you can simply walk the inheritence tree and get all of the inherited fields with the following code snippet:

``` java
private List<Field> getAllFields(Class<? extends Model> type) {
    List<Field> result = new ArrayList<Field>();

    Class<?> i = type;
    while (i != null && i != Model.class) {
        result.addAll(Arrays.asList(i.getDeclaredFields()));
        i = i.getSuperclass();
    }

    return result;
}
```

**Comment by luanntvn** [comment]
I got this problem few months ago and solved it with similar WonderCsabo's way. Today I reviewed and posted at http://luan-itworld.blogspot.com/2013/08/activeandroid-model-inheritance.html

Then I found this issue here :)

**Comment by bkhall** [comment]
@WonderCsabo 

I agree that your solution gets the fields from each parent class without requiring them to be public, that's true. I would also agree that using public fields is very bad practice. However, the examples shown in the readme of this project already show the use of public fields in classes that extend Model. It's only in that context that I made my post.

Perhaps the examples should be updates to show proper use of private fields with getters and setters.

**Comment by agrosner** [comment]
I can put up a merge request that solves this whole issue as we have implemented things with similar fashion using reflection.

**Comment by eranation** [comment]
Any updates? :)

**Comment by domsu** [comment]
I have just tested model inheritance and it is working in version 3.0.1

**Comment by eranation** [comment]
Thanks! is there an example anywhere? couldn't find anything :/

**Comment by boxlady** [comment]
Yeah is there an example? I'v tried this with the newest and I'm still getting the results that @a99 got.

**Comment by agrosner** [comment]
If youre having trouble with this library,  i'd check out https://github.com/Raizlabs/DBFlow. Maybe it'll work best for you

**Comment by boxlady** [comment]
Hey thanks, seems to be what I'm looking for.

**Comment by JordyCuan** [comment]
@a99 
@domsu 

Hi All! 

I am having some troubles using Inheritance with AA, my specific error is what @a99 says:

> If I create 3 Dogs, and then 2 Cats
> I expect 5 entries in Pets table.
> I expect ids in Pets to be 1, 2, 3, 4, 5
> I expect the ids in Dogs to be 1, 2, 3
> I expect the ids in Cats to be 4, 5
> 
> Currently (as of 20/04/13 on master branch) the result is:
> 0 in Pets
> 3 in Dogs -> ids: 1, 2, 3
> 2 in Cats -> ids: 1, 2

What I have is:

Report extends Model
NutritionalReport extends Report
PsychologicalReport extends Report

Each report has its date inherited from Report so I want to show all reports sorted by date but when I call:

```
new Select().from(Report.class).orderBy("date ASC").execute();
```

**It returns an empty list**

But if I call this:

```
List<Report> list = new ArrayList<>();
list.addAll(new Select().from(NutritionalReport.class).orderBy("date ASC").execute());
list.addAll(new Select().from(PsychologicalReport.class).orderBy("date ASC").execute());
```

the returned list is unsorted (partially ordered, sort the list is not an option)

any suggestions?
